### PR TITLE
Remove callbag dependencies

### PR DESCRIPTION
**Pull request by hnordt**

### CODE REVIEW

**Comment by hnordt** [comment]
@pedronauck I think we should run some benchmark to make sure I didn't introduce performance degradation.

**Comment by hnordt** [comment]
@pedronauck I updated the code so now we match the Redux store emitter implementation, I don't think we'll have performance issues as Redux is widely used.

**Comment by micnic** [comment]
I came here to see  if some dependencies can be removed, as such small API should be done without any, glad to see that somebody took care of this. I have just one nit, by design `set()` should emit only one value, in your case you allow multiple values which internally are transformed in an array, which should actually impact performance, please see this: https://www.typescriptlang.org/play/index.html#src=const%20fn%20%3D%20(...args)%20%3D%3E%20%7B%0D%0A%20%20%20%20console.log(...args)%3B%0D%0A%7D

I would recommend to revert the change for the `emit()` function

**Comment by hnordt** [comment]
@micnic good catch mate. I'm fixing it now. Thank you! <3

**Comment by hnordt** [comment]
A big round of applause to @gtkatakura, which ran a benchmark for us.

https://gist.github.com/gtkatakura/0f59a763bc513bbf8928fe4ccc1900fa

`createEmitter` is even faster. 🤟🏻

**Comment by sijad** [comment]
Any news?

**Comment by ggviana** [comment]
This PR fixes #15 indirectly :tada:

**Pull request merged**
